/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterHostCreateHost struct for VcenterHostCreateHost
type VcenterHostCreateHost struct {
	Spec *VcenterHostCreateSpec `json:"spec,omitempty"`
}

// NewVcenterHostCreateHost instantiates a new VcenterHostCreateHost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterHostCreateHost() *VcenterHostCreateHost {
	this := VcenterHostCreateHost{}
	return &this
}

// NewVcenterHostCreateHostWithDefaults instantiates a new VcenterHostCreateHost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterHostCreateHostWithDefaults() *VcenterHostCreateHost {
	this := VcenterHostCreateHost{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VcenterHostCreateHost) GetSpec() VcenterHostCreateSpec {
	if o == nil || o.Spec == nil {
		var ret VcenterHostCreateSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterHostCreateHost) GetSpecOk() (*VcenterHostCreateSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VcenterHostCreateHost) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given VcenterHostCreateSpec and assigns it to the Spec field.
func (o *VcenterHostCreateHost) SetSpec(v VcenterHostCreateSpec) {
	o.Spec = &v
}

func (o VcenterHostCreateHost) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterHostCreateHost struct {
	value *VcenterHostCreateHost
	isSet bool
}

func (v NullableVcenterHostCreateHost) Get() *VcenterHostCreateHost {
	return v.value
}

func (v *NullableVcenterHostCreateHost) Set(val *VcenterHostCreateHost) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterHostCreateHost) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterHostCreateHost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterHostCreateHost(val *VcenterHostCreateHost) *NullableVcenterHostCreateHost {
	return &NullableVcenterHostCreateHost{value: val, isSet: true}
}

func (v NullableVcenterHostCreateHost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterHostCreateHost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


