/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterNamespaceManagementSupportBundleToken struct for VcenterNamespaceManagementSupportBundleToken
type VcenterNamespaceManagementSupportBundleToken struct {
	// A one-time, short-lived token required in the HTTP header of the request to the url. This token needs to be passed in as a header with the name \"wcp-support-bundle-token\".
	Token string `json:"token"`
	// Expiry time of the token
	Expiry string `json:"expiry"`
}

// NewVcenterNamespaceManagementSupportBundleToken instantiates a new VcenterNamespaceManagementSupportBundleToken object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterNamespaceManagementSupportBundleToken(token string, expiry string) *VcenterNamespaceManagementSupportBundleToken {
	this := VcenterNamespaceManagementSupportBundleToken{}
	this.Token = token
	this.Expiry = expiry
	return &this
}

// NewVcenterNamespaceManagementSupportBundleTokenWithDefaults instantiates a new VcenterNamespaceManagementSupportBundleToken object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterNamespaceManagementSupportBundleTokenWithDefaults() *VcenterNamespaceManagementSupportBundleToken {
	this := VcenterNamespaceManagementSupportBundleToken{}
	return &this
}

// GetToken returns the Token field value
func (o *VcenterNamespaceManagementSupportBundleToken) GetToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Token
}

// GetTokenOk returns a tuple with the Token field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementSupportBundleToken) GetTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Token, true
}

// SetToken sets field value
func (o *VcenterNamespaceManagementSupportBundleToken) SetToken(v string) {
	o.Token = v
}

// GetExpiry returns the Expiry field value
func (o *VcenterNamespaceManagementSupportBundleToken) GetExpiry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Expiry
}

// GetExpiryOk returns a tuple with the Expiry field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementSupportBundleToken) GetExpiryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Expiry, true
}

// SetExpiry sets field value
func (o *VcenterNamespaceManagementSupportBundleToken) SetExpiry(v string) {
	o.Expiry = v
}

func (o VcenterNamespaceManagementSupportBundleToken) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["token"] = o.Token
	}
	if true {
		toSerialize["expiry"] = o.Expiry
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterNamespaceManagementSupportBundleToken struct {
	value *VcenterNamespaceManagementSupportBundleToken
	isSet bool
}

func (v NullableVcenterNamespaceManagementSupportBundleToken) Get() *VcenterNamespaceManagementSupportBundleToken {
	return v.value
}

func (v *NullableVcenterNamespaceManagementSupportBundleToken) Set(val *VcenterNamespaceManagementSupportBundleToken) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterNamespaceManagementSupportBundleToken) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterNamespaceManagementSupportBundleToken) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterNamespaceManagementSupportBundleToken(val *VcenterNamespaceManagementSupportBundleToken) *NullableVcenterNamespaceManagementSupportBundleToken {
	return &NullableVcenterNamespaceManagementSupportBundleToken{value: val, isSet: true}
}

func (v NullableVcenterNamespaceManagementSupportBundleToken) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterNamespaceManagementSupportBundleToken) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


