/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems struct for VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems
type VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems struct {
	Spec *VcenterVmTemplateLibraryItemsCreateSpec `json:"spec,omitempty"`
}

// NewVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems instantiates a new VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems() *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems {
	this := VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems{}
	return &this
}

// NewVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItemsWithDefaults instantiates a new VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItemsWithDefaults() *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems {
	this := VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) GetSpec() VcenterVmTemplateLibraryItemsCreateSpec {
	if o == nil || o.Spec == nil {
		var ret VcenterVmTemplateLibraryItemsCreateSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) GetSpecOk() (*VcenterVmTemplateLibraryItemsCreateSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given VcenterVmTemplateLibraryItemsCreateSpec and assigns it to the Spec field.
func (o *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) SetSpec(v VcenterVmTemplateLibraryItemsCreateSpec) {
	o.Spec = &v
}

func (o VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems struct {
	value *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems
	isSet bool
}

func (v NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) Get() *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems {
	return v.value
}

func (v *NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) Set(val *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems(val *VcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) *NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems {
	return &NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems{value: val, isSet: true}
}

func (v NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterVmTemplateLibraryItemsCreateVmTemplateLibraryItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


