/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterCertificateManagementVcenterTrustedRootChainsSummary struct for VcenterCertificateManagementVcenterTrustedRootChainsSummary
type VcenterCertificateManagementVcenterTrustedRootChainsSummary struct {
	// Unique identifier for chain.
	Chain string `json:"chain"`
}

// NewVcenterCertificateManagementVcenterTrustedRootChainsSummary instantiates a new VcenterCertificateManagementVcenterTrustedRootChainsSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterCertificateManagementVcenterTrustedRootChainsSummary(chain string) *VcenterCertificateManagementVcenterTrustedRootChainsSummary {
	this := VcenterCertificateManagementVcenterTrustedRootChainsSummary{}
	this.Chain = chain
	return &this
}

// NewVcenterCertificateManagementVcenterTrustedRootChainsSummaryWithDefaults instantiates a new VcenterCertificateManagementVcenterTrustedRootChainsSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterCertificateManagementVcenterTrustedRootChainsSummaryWithDefaults() *VcenterCertificateManagementVcenterTrustedRootChainsSummary {
	this := VcenterCertificateManagementVcenterTrustedRootChainsSummary{}
	return &this
}

// GetChain returns the Chain field value
func (o *VcenterCertificateManagementVcenterTrustedRootChainsSummary) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *VcenterCertificateManagementVcenterTrustedRootChainsSummary) GetChainOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *VcenterCertificateManagementVcenterTrustedRootChainsSummary) SetChain(v string) {
	o.Chain = v
}

func (o VcenterCertificateManagementVcenterTrustedRootChainsSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["chain"] = o.Chain
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary struct {
	value *VcenterCertificateManagementVcenterTrustedRootChainsSummary
	isSet bool
}

func (v NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) Get() *VcenterCertificateManagementVcenterTrustedRootChainsSummary {
	return v.value
}

func (v *NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) Set(val *VcenterCertificateManagementVcenterTrustedRootChainsSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterCertificateManagementVcenterTrustedRootChainsSummary(val *VcenterCertificateManagementVcenterTrustedRootChainsSummary) *NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary {
	return &NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary{value: val, isSet: true}
}

func (v NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterCertificateManagementVcenterTrustedRootChainsSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


