/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary struct for VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary
type VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary struct {
	SummaryType VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType `json:"summary_type"`
	// The trusted ESX on which the service runs. This field is optional and it is only relevant when the value of Kms.Summary.summary-type is one of BRIEF, NORMAL, or FULL. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: HostSystem. When operations return a value of this structure as a result, the field will be an identifier for the resource type: HostSystem.
	Host *string `json:"host,omitempty"`
	Address *VcenterTrustedInfrastructureNetworkAddress `json:"address,omitempty"`
	// The group ID determines which Attestation Service instances this Key Provider Service can communicate with. This field is optional and it is only relevant when the value of Kms.Summary.summary-type is one of NORMAL or FULL.
	Group *string `json:"group,omitempty"`
	// The opaque string identifier of the cluster in which the Key Provider Service is part of. This field is optional and it is only relevant when the value of Kms.Summary.summary-type is one of NORMAL or FULL.
	Cluster *string `json:"cluster,omitempty"`
	TrustedCA *VcenterTrustedInfrastructureX509CertChain `json:"trusted_CA,omitempty"`
}

// NewVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary instantiates a new VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary(summaryType VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType) *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary {
	this := VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary{}
	this.SummaryType = summaryType
	return &this
}

// NewVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryWithDefaults instantiates a new VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryWithDefaults() *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary {
	this := VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary{}
	return &this
}

// GetSummaryType returns the SummaryType field value
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetSummaryType() VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType {
	if o == nil {
		var ret VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType
		return ret
	}

	return o.SummaryType
}

// GetSummaryTypeOk returns a tuple with the SummaryType field value
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetSummaryTypeOk() (*VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SummaryType, true
}

// SetSummaryType sets field value
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetSummaryType(v VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummaryType) {
	o.SummaryType = v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetHost(v string) {
	o.Host = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetAddress() VcenterTrustedInfrastructureNetworkAddress {
	if o == nil || o.Address == nil {
		var ret VcenterTrustedInfrastructureNetworkAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetAddressOk() (*VcenterTrustedInfrastructureNetworkAddress, bool) {
	if o == nil || o.Address == nil {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) HasAddress() bool {
	if o != nil && o.Address != nil {
		return true
	}

	return false
}

// SetAddress gets a reference to the given VcenterTrustedInfrastructureNetworkAddress and assigns it to the Address field.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetAddress(v VcenterTrustedInfrastructureNetworkAddress) {
	o.Address = &v
}

// GetGroup returns the Group field value if set, zero value otherwise.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetGroup() string {
	if o == nil || o.Group == nil {
		var ret string
		return ret
	}
	return *o.Group
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetGroupOk() (*string, bool) {
	if o == nil || o.Group == nil {
		return nil, false
	}
	return o.Group, true
}

// HasGroup returns a boolean if a field has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) HasGroup() bool {
	if o != nil && o.Group != nil {
		return true
	}

	return false
}

// SetGroup gets a reference to the given string and assigns it to the Group field.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetGroup(v string) {
	o.Group = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetCluster(v string) {
	o.Cluster = &v
}

// GetTrustedCA returns the TrustedCA field value if set, zero value otherwise.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetTrustedCA() VcenterTrustedInfrastructureX509CertChain {
	if o == nil || o.TrustedCA == nil {
		var ret VcenterTrustedInfrastructureX509CertChain
		return ret
	}
	return *o.TrustedCA
}

// GetTrustedCAOk returns a tuple with the TrustedCA field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) GetTrustedCAOk() (*VcenterTrustedInfrastructureX509CertChain, bool) {
	if o == nil || o.TrustedCA == nil {
		return nil, false
	}
	return o.TrustedCA, true
}

// HasTrustedCA returns a boolean if a field has been set.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) HasTrustedCA() bool {
	if o != nil && o.TrustedCA != nil {
		return true
	}

	return false
}

// SetTrustedCA gets a reference to the given VcenterTrustedInfrastructureX509CertChain and assigns it to the TrustedCA field.
func (o *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) SetTrustedCA(v VcenterTrustedInfrastructureX509CertChain) {
	o.TrustedCA = &v
}

func (o VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["summary_type"] = o.SummaryType
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.Address != nil {
		toSerialize["address"] = o.Address
	}
	if o.Group != nil {
		toSerialize["group"] = o.Group
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	if o.TrustedCA != nil {
		toSerialize["trusted_CA"] = o.TrustedCA
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary struct {
	value *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary
	isSet bool
}

func (v NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) Get() *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary {
	return v.value
}

func (v *NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) Set(val *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary(val *VcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) *NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary {
	return &NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary{value: val, isSet: true}
}

func (v NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterTrustedInfrastructureTrustAuthorityHostsKmsSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


