/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentMigrateVcsaEmbeddedSpec struct for VcenterDeploymentMigrateVcsaEmbeddedSpec
type VcenterDeploymentMigrateVcsaEmbeddedSpec struct {
	// Customer experience improvement program should be enabled or disabled for this embedded vCenter Server migration.
	CeipEnabled bool `json:"ceip_enabled"`
}

// NewVcenterDeploymentMigrateVcsaEmbeddedSpec instantiates a new VcenterDeploymentMigrateVcsaEmbeddedSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentMigrateVcsaEmbeddedSpec(ceipEnabled bool) *VcenterDeploymentMigrateVcsaEmbeddedSpec {
	this := VcenterDeploymentMigrateVcsaEmbeddedSpec{}
	this.CeipEnabled = ceipEnabled
	return &this
}

// NewVcenterDeploymentMigrateVcsaEmbeddedSpecWithDefaults instantiates a new VcenterDeploymentMigrateVcsaEmbeddedSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentMigrateVcsaEmbeddedSpecWithDefaults() *VcenterDeploymentMigrateVcsaEmbeddedSpec {
	this := VcenterDeploymentMigrateVcsaEmbeddedSpec{}
	return &this
}

// GetCeipEnabled returns the CeipEnabled field value
func (o *VcenterDeploymentMigrateVcsaEmbeddedSpec) GetCeipEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CeipEnabled
}

// GetCeipEnabledOk returns a tuple with the CeipEnabled field value
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentMigrateVcsaEmbeddedSpec) GetCeipEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CeipEnabled, true
}

// SetCeipEnabled sets field value
func (o *VcenterDeploymentMigrateVcsaEmbeddedSpec) SetCeipEnabled(v bool) {
	o.CeipEnabled = v
}

func (o VcenterDeploymentMigrateVcsaEmbeddedSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ceip_enabled"] = o.CeipEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentMigrateVcsaEmbeddedSpec struct {
	value *VcenterDeploymentMigrateVcsaEmbeddedSpec
	isSet bool
}

func (v NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) Get() *VcenterDeploymentMigrateVcsaEmbeddedSpec {
	return v.value
}

func (v *NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) Set(val *VcenterDeploymentMigrateVcsaEmbeddedSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentMigrateVcsaEmbeddedSpec(val *VcenterDeploymentMigrateVcsaEmbeddedSpec) *NullableVcenterDeploymentMigrateVcsaEmbeddedSpec {
	return &NullableVcenterDeploymentMigrateVcsaEmbeddedSpec{value: val, isSet: true}
}

func (v NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentMigrateVcsaEmbeddedSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


