/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentMigratePscSpec struct for VcenterDeploymentMigratePscSpec
type VcenterDeploymentMigratePscSpec struct {
	// Customer experience improvement program should be enabled or disabled for this Platform Services Controller migration.
	CeipEnabled bool `json:"ceip_enabled"`
}

// NewVcenterDeploymentMigratePscSpec instantiates a new VcenterDeploymentMigratePscSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentMigratePscSpec(ceipEnabled bool) *VcenterDeploymentMigratePscSpec {
	this := VcenterDeploymentMigratePscSpec{}
	this.CeipEnabled = ceipEnabled
	return &this
}

// NewVcenterDeploymentMigratePscSpecWithDefaults instantiates a new VcenterDeploymentMigratePscSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentMigratePscSpecWithDefaults() *VcenterDeploymentMigratePscSpec {
	this := VcenterDeploymentMigratePscSpec{}
	return &this
}

// GetCeipEnabled returns the CeipEnabled field value
func (o *VcenterDeploymentMigratePscSpec) GetCeipEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CeipEnabled
}

// GetCeipEnabledOk returns a tuple with the CeipEnabled field value
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentMigratePscSpec) GetCeipEnabledOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CeipEnabled, true
}

// SetCeipEnabled sets field value
func (o *VcenterDeploymentMigratePscSpec) SetCeipEnabled(v bool) {
	o.CeipEnabled = v
}

func (o VcenterDeploymentMigratePscSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ceip_enabled"] = o.CeipEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentMigratePscSpec struct {
	value *VcenterDeploymentMigratePscSpec
	isSet bool
}

func (v NullableVcenterDeploymentMigratePscSpec) Get() *VcenterDeploymentMigratePscSpec {
	return v.value
}

func (v *NullableVcenterDeploymentMigratePscSpec) Set(val *VcenterDeploymentMigratePscSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentMigratePscSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentMigratePscSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentMigratePscSpec(val *VcenterDeploymentMigratePscSpec) *NullableVcenterDeploymentMigratePscSpec {
	return &NullableVcenterDeploymentMigratePscSpec{value: val, isSet: true}
}

func (v NullableVcenterDeploymentMigratePscSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentMigratePscSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


