/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp struct for VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp
type VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp struct {
	Value []VcenterVmTemplateLibraryItemsVersionsSummary `json:"value"`
}

// NewVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp instantiates a new VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp(value []VcenterVmTemplateLibraryItemsVersionsSummary) *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp {
	this := VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp{}
	this.Value = value
	return &this
}

// NewVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsRespWithDefaults instantiates a new VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsRespWithDefaults() *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp {
	this := VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp{}
	return &this
}

// GetValue returns the Value field value
func (o *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) GetValue() []VcenterVmTemplateLibraryItemsVersionsSummary {
	if o == nil {
		var ret []VcenterVmTemplateLibraryItemsVersionsSummary
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) GetValueOk() (*[]VcenterVmTemplateLibraryItemsVersionsSummary, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) SetValue(v []VcenterVmTemplateLibraryItemsVersionsSummary) {
	o.Value = v
}

func (o VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp struct {
	value *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp
	isSet bool
}

func (v NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) Get() *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp {
	return v.value
}

func (v *NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) Set(val *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp(val *VcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) *NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp {
	return &NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp{value: val, isSet: true}
}

func (v NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterVmTemplateLibraryItemsVersionsListVmTemplateLibraryItemsVersionsResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


