/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterStoragePoliciesVMInfo struct for VcenterStoragePoliciesVMInfo
type VcenterStoragePoliciesVMInfo struct {
	// Flag to indicate whether or not the virtual machine home is associated with the given storage policy.
	VmHome bool `json:"vm_home"`
	// List of the virtual disks that are associated with the given storage policy. When clients pass a value of this structure as a parameter, the field must contain identifiers for the resource type: vcenter.vm.hardware.Disk. When operations return a value of this structure as a result, the field will contain identifiers for the resource type: vcenter.vm.hardware.Disk.
	Disks []string `json:"disks"`
}

// NewVcenterStoragePoliciesVMInfo instantiates a new VcenterStoragePoliciesVMInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterStoragePoliciesVMInfo(vmHome bool, disks []string) *VcenterStoragePoliciesVMInfo {
	this := VcenterStoragePoliciesVMInfo{}
	this.VmHome = vmHome
	this.Disks = disks
	return &this
}

// NewVcenterStoragePoliciesVMInfoWithDefaults instantiates a new VcenterStoragePoliciesVMInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterStoragePoliciesVMInfoWithDefaults() *VcenterStoragePoliciesVMInfo {
	this := VcenterStoragePoliciesVMInfo{}
	return &this
}

// GetVmHome returns the VmHome field value
func (o *VcenterStoragePoliciesVMInfo) GetVmHome() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.VmHome
}

// GetVmHomeOk returns a tuple with the VmHome field value
// and a boolean to check if the value has been set.
func (o *VcenterStoragePoliciesVMInfo) GetVmHomeOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.VmHome, true
}

// SetVmHome sets field value
func (o *VcenterStoragePoliciesVMInfo) SetVmHome(v bool) {
	o.VmHome = v
}

// GetDisks returns the Disks field value
func (o *VcenterStoragePoliciesVMInfo) GetDisks() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Disks
}

// GetDisksOk returns a tuple with the Disks field value
// and a boolean to check if the value has been set.
func (o *VcenterStoragePoliciesVMInfo) GetDisksOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Disks, true
}

// SetDisks sets field value
func (o *VcenterStoragePoliciesVMInfo) SetDisks(v []string) {
	o.Disks = v
}

func (o VcenterStoragePoliciesVMInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["vm_home"] = o.VmHome
	}
	if true {
		toSerialize["disks"] = o.Disks
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterStoragePoliciesVMInfo struct {
	value *VcenterStoragePoliciesVMInfo
	isSet bool
}

func (v NullableVcenterStoragePoliciesVMInfo) Get() *VcenterStoragePoliciesVMInfo {
	return v.value
}

func (v *NullableVcenterStoragePoliciesVMInfo) Set(val *VcenterStoragePoliciesVMInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterStoragePoliciesVMInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterStoragePoliciesVMInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterStoragePoliciesVMInfo(val *VcenterStoragePoliciesVMInfo) *NullableVcenterStoragePoliciesVMInfo {
	return &NullableVcenterStoragePoliciesVMInfo{value: val, isSet: true}
}

func (v NullableVcenterStoragePoliciesVMInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterStoragePoliciesVMInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


