/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec struct for VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec
type VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec struct {
	// Identifier of the vSphere Distributed Portgroup backing the vSphere network object. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: Network. When operations return a value of this structure as a result, the field will be an identifier for the resource type: Network.
	Portgroup string `json:"portgroup"`
	// Usable IP pools on this network.
	AddressRanges []VcenterNamespaceManagementIPRange `json:"address_ranges"`
	// Gateway for the network.
	Gateway string `json:"gateway"`
	// Subnet mask of the network.
	SubnetMask string `json:"subnet_mask"`
}

// NewVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec instantiates a new VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec(portgroup string, addressRanges []VcenterNamespaceManagementIPRange, gateway string, subnetMask string) *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec {
	this := VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec{}
	this.Portgroup = portgroup
	this.AddressRanges = addressRanges
	this.Gateway = gateway
	this.SubnetMask = subnetMask
	return &this
}

// NewVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpecWithDefaults instantiates a new VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpecWithDefaults() *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec {
	this := VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec{}
	return &this
}

// GetPortgroup returns the Portgroup field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetPortgroup() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Portgroup
}

// GetPortgroupOk returns a tuple with the Portgroup field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetPortgroupOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Portgroup, true
}

// SetPortgroup sets field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) SetPortgroup(v string) {
	o.Portgroup = v
}

// GetAddressRanges returns the AddressRanges field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetAddressRanges() []VcenterNamespaceManagementIPRange {
	if o == nil {
		var ret []VcenterNamespaceManagementIPRange
		return ret
	}

	return o.AddressRanges
}

// GetAddressRangesOk returns a tuple with the AddressRanges field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetAddressRangesOk() (*[]VcenterNamespaceManagementIPRange, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AddressRanges, true
}

// SetAddressRanges sets field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) SetAddressRanges(v []VcenterNamespaceManagementIPRange) {
	o.AddressRanges = v
}

// GetGateway returns the Gateway field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetGateway() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Gateway
}

// GetGatewayOk returns a tuple with the Gateway field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetGatewayOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Gateway, true
}

// SetGateway sets field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) SetGateway(v string) {
	o.Gateway = v
}

// GetSubnetMask returns the SubnetMask field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetSubnetMask() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubnetMask
}

// GetSubnetMaskOk returns a tuple with the SubnetMask field value
// and a boolean to check if the value has been set.
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) GetSubnetMaskOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SubnetMask, true
}

// SetSubnetMask sets field value
func (o *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) SetSubnetMask(v string) {
	o.SubnetMask = v
}

func (o VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["portgroup"] = o.Portgroup
	}
	if true {
		toSerialize["address_ranges"] = o.AddressRanges
	}
	if true {
		toSerialize["gateway"] = o.Gateway
	}
	if true {
		toSerialize["subnet_mask"] = o.SubnetMask
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec struct {
	value *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec
	isSet bool
}

func (v NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) Get() *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec {
	return v.value
}

func (v *NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) Set(val *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec(val *VcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) *NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec {
	return &NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec{value: val, isSet: true}
}

func (v NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterNamespaceManagementNetworksVsphereDVPGNetworkCreateSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


