/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterCryptoManagerHostsKmsProvidersInfo struct for VcenterCryptoManagerHostsKmsProvidersInfo
type VcenterCryptoManagerHostsKmsProvidersInfo struct {
	Health VcenterCryptoManagerHostsKmsProvidersHealth `json:"health"`
	// Details regarding the health status of the provider. When the provider Providers.Health is not OK or NONE, this field will provide actionable descriptions of the issues.
	Details []VapiStdLocalizableMessage `json:"details"`
	Type VcenterCryptoManagerHostsKmsProvidersType `json:"type"`
	NativeInfo *VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo `json:"native_info,omitempty"`
}

// NewVcenterCryptoManagerHostsKmsProvidersInfo instantiates a new VcenterCryptoManagerHostsKmsProvidersInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterCryptoManagerHostsKmsProvidersInfo(health VcenterCryptoManagerHostsKmsProvidersHealth, details []VapiStdLocalizableMessage, type_ VcenterCryptoManagerHostsKmsProvidersType) *VcenterCryptoManagerHostsKmsProvidersInfo {
	this := VcenterCryptoManagerHostsKmsProvidersInfo{}
	this.Health = health
	this.Details = details
	this.Type = type_
	return &this
}

// NewVcenterCryptoManagerHostsKmsProvidersInfoWithDefaults instantiates a new VcenterCryptoManagerHostsKmsProvidersInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterCryptoManagerHostsKmsProvidersInfoWithDefaults() *VcenterCryptoManagerHostsKmsProvidersInfo {
	this := VcenterCryptoManagerHostsKmsProvidersInfo{}
	return &this
}

// GetHealth returns the Health field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetHealth() VcenterCryptoManagerHostsKmsProvidersHealth {
	if o == nil {
		var ret VcenterCryptoManagerHostsKmsProvidersHealth
		return ret
	}

	return o.Health
}

// GetHealthOk returns a tuple with the Health field value
// and a boolean to check if the value has been set.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetHealthOk() (*VcenterCryptoManagerHostsKmsProvidersHealth, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Health, true
}

// SetHealth sets field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) SetHealth(v VcenterCryptoManagerHostsKmsProvidersHealth) {
	o.Health = v
}

// GetDetails returns the Details field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetDetails() []VapiStdLocalizableMessage {
	if o == nil {
		var ret []VapiStdLocalizableMessage
		return ret
	}

	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value
// and a boolean to check if the value has been set.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetDetailsOk() (*[]VapiStdLocalizableMessage, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Details, true
}

// SetDetails sets field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) SetDetails(v []VapiStdLocalizableMessage) {
	o.Details = v
}

// GetType returns the Type field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetType() VcenterCryptoManagerHostsKmsProvidersType {
	if o == nil {
		var ret VcenterCryptoManagerHostsKmsProvidersType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetTypeOk() (*VcenterCryptoManagerHostsKmsProvidersType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) SetType(v VcenterCryptoManagerHostsKmsProvidersType) {
	o.Type = v
}

// GetNativeInfo returns the NativeInfo field value if set, zero value otherwise.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetNativeInfo() VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo {
	if o == nil || o.NativeInfo == nil {
		var ret VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo
		return ret
	}
	return *o.NativeInfo
}

// GetNativeInfoOk returns a tuple with the NativeInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) GetNativeInfoOk() (*VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo, bool) {
	if o == nil || o.NativeInfo == nil {
		return nil, false
	}
	return o.NativeInfo, true
}

// HasNativeInfo returns a boolean if a field has been set.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) HasNativeInfo() bool {
	if o != nil && o.NativeInfo != nil {
		return true
	}

	return false
}

// SetNativeInfo gets a reference to the given VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo and assigns it to the NativeInfo field.
func (o *VcenterCryptoManagerHostsKmsProvidersInfo) SetNativeInfo(v VcenterCryptoManagerHostsKmsProvidersNativeProviderInfo) {
	o.NativeInfo = &v
}

func (o VcenterCryptoManagerHostsKmsProvidersInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["health"] = o.Health
	}
	if true {
		toSerialize["details"] = o.Details
	}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.NativeInfo != nil {
		toSerialize["native_info"] = o.NativeInfo
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterCryptoManagerHostsKmsProvidersInfo struct {
	value *VcenterCryptoManagerHostsKmsProvidersInfo
	isSet bool
}

func (v NullableVcenterCryptoManagerHostsKmsProvidersInfo) Get() *VcenterCryptoManagerHostsKmsProvidersInfo {
	return v.value
}

func (v *NullableVcenterCryptoManagerHostsKmsProvidersInfo) Set(val *VcenterCryptoManagerHostsKmsProvidersInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterCryptoManagerHostsKmsProvidersInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterCryptoManagerHostsKmsProvidersInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterCryptoManagerHostsKmsProvidersInfo(val *VcenterCryptoManagerHostsKmsProvidersInfo) *NullableVcenterCryptoManagerHostsKmsProvidersInfo {
	return &NullableVcenterCryptoManagerHostsKmsProvidersInfo{value: val, isSet: true}
}

func (v NullableVcenterCryptoManagerHostsKmsProvidersInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterCryptoManagerHostsKmsProvidersInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


