/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentQuestionAnswerDeploymentQuestion struct for VcenterDeploymentQuestionAnswerDeploymentQuestion
type VcenterDeploymentQuestionAnswerDeploymentQuestion struct {
	Spec *VcenterDeploymentQuestionAnswerSpec `json:"spec,omitempty"`
}

// NewVcenterDeploymentQuestionAnswerDeploymentQuestion instantiates a new VcenterDeploymentQuestionAnswerDeploymentQuestion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentQuestionAnswerDeploymentQuestion() *VcenterDeploymentQuestionAnswerDeploymentQuestion {
	this := VcenterDeploymentQuestionAnswerDeploymentQuestion{}
	return &this
}

// NewVcenterDeploymentQuestionAnswerDeploymentQuestionWithDefaults instantiates a new VcenterDeploymentQuestionAnswerDeploymentQuestion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentQuestionAnswerDeploymentQuestionWithDefaults() *VcenterDeploymentQuestionAnswerDeploymentQuestion {
	this := VcenterDeploymentQuestionAnswerDeploymentQuestion{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VcenterDeploymentQuestionAnswerDeploymentQuestion) GetSpec() VcenterDeploymentQuestionAnswerSpec {
	if o == nil || o.Spec == nil {
		var ret VcenterDeploymentQuestionAnswerSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentQuestionAnswerDeploymentQuestion) GetSpecOk() (*VcenterDeploymentQuestionAnswerSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VcenterDeploymentQuestionAnswerDeploymentQuestion) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given VcenterDeploymentQuestionAnswerSpec and assigns it to the Spec field.
func (o *VcenterDeploymentQuestionAnswerDeploymentQuestion) SetSpec(v VcenterDeploymentQuestionAnswerSpec) {
	o.Spec = &v
}

func (o VcenterDeploymentQuestionAnswerDeploymentQuestion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentQuestionAnswerDeploymentQuestion struct {
	value *VcenterDeploymentQuestionAnswerDeploymentQuestion
	isSet bool
}

func (v NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) Get() *VcenterDeploymentQuestionAnswerDeploymentQuestion {
	return v.value
}

func (v *NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) Set(val *VcenterDeploymentQuestionAnswerDeploymentQuestion) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentQuestionAnswerDeploymentQuestion(val *VcenterDeploymentQuestionAnswerDeploymentQuestion) *NullableVcenterDeploymentQuestionAnswerDeploymentQuestion {
	return &NullableVcenterDeploymentQuestionAnswerDeploymentQuestion{value: val, isSet: true}
}

func (v NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentQuestionAnswerDeploymentQuestion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


