/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentInstallGetDeploymentInstallResp struct for VcenterDeploymentInstallGetDeploymentInstallResp
type VcenterDeploymentInstallGetDeploymentInstallResp struct {
	Value VcenterDeploymentInstallInstallSpec `json:"value"`
}

// NewVcenterDeploymentInstallGetDeploymentInstallResp instantiates a new VcenterDeploymentInstallGetDeploymentInstallResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentInstallGetDeploymentInstallResp(value VcenterDeploymentInstallInstallSpec) *VcenterDeploymentInstallGetDeploymentInstallResp {
	this := VcenterDeploymentInstallGetDeploymentInstallResp{}
	this.Value = value
	return &this
}

// NewVcenterDeploymentInstallGetDeploymentInstallRespWithDefaults instantiates a new VcenterDeploymentInstallGetDeploymentInstallResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentInstallGetDeploymentInstallRespWithDefaults() *VcenterDeploymentInstallGetDeploymentInstallResp {
	this := VcenterDeploymentInstallGetDeploymentInstallResp{}
	return &this
}

// GetValue returns the Value field value
func (o *VcenterDeploymentInstallGetDeploymentInstallResp) GetValue() VcenterDeploymentInstallInstallSpec {
	if o == nil {
		var ret VcenterDeploymentInstallInstallSpec
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentInstallGetDeploymentInstallResp) GetValueOk() (*VcenterDeploymentInstallInstallSpec, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VcenterDeploymentInstallGetDeploymentInstallResp) SetValue(v VcenterDeploymentInstallInstallSpec) {
	o.Value = v
}

func (o VcenterDeploymentInstallGetDeploymentInstallResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentInstallGetDeploymentInstallResp struct {
	value *VcenterDeploymentInstallGetDeploymentInstallResp
	isSet bool
}

func (v NullableVcenterDeploymentInstallGetDeploymentInstallResp) Get() *VcenterDeploymentInstallGetDeploymentInstallResp {
	return v.value
}

func (v *NullableVcenterDeploymentInstallGetDeploymentInstallResp) Set(val *VcenterDeploymentInstallGetDeploymentInstallResp) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentInstallGetDeploymentInstallResp) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentInstallGetDeploymentInstallResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentInstallGetDeploymentInstallResp(val *VcenterDeploymentInstallGetDeploymentInstallResp) *NullableVcenterDeploymentInstallGetDeploymentInstallResp {
	return &NullableVcenterDeploymentInstallGetDeploymentInstallResp{value: val, isSet: true}
}

func (v NullableVcenterDeploymentInstallGetDeploymentInstallResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentInstallGetDeploymentInstallResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


