/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterVmStoragePolicyDiskPolicySpec struct for VcenterVmStoragePolicyDiskPolicySpec
type VcenterVmStoragePolicyDiskPolicySpec struct {
	Type VcenterVmStoragePolicyDiskPolicySpecPolicyType `json:"type"`
	// Storage Policy identification. This field is optional and it is only relevant when the value of Policy.DiskPolicySpec.type is USE_SPECIFIED_POLICY. When clients pass a value of this structure as a parameter, the field must be an identifier for the resource type: vcenter.StoragePolicy. When operations return a value of this structure as a result, the field will be an identifier for the resource type: vcenter.StoragePolicy.
	Policy *string `json:"policy,omitempty"`
}

// NewVcenterVmStoragePolicyDiskPolicySpec instantiates a new VcenterVmStoragePolicyDiskPolicySpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterVmStoragePolicyDiskPolicySpec(type_ VcenterVmStoragePolicyDiskPolicySpecPolicyType) *VcenterVmStoragePolicyDiskPolicySpec {
	this := VcenterVmStoragePolicyDiskPolicySpec{}
	this.Type = type_
	return &this
}

// NewVcenterVmStoragePolicyDiskPolicySpecWithDefaults instantiates a new VcenterVmStoragePolicyDiskPolicySpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterVmStoragePolicyDiskPolicySpecWithDefaults() *VcenterVmStoragePolicyDiskPolicySpec {
	this := VcenterVmStoragePolicyDiskPolicySpec{}
	return &this
}

// GetType returns the Type field value
func (o *VcenterVmStoragePolicyDiskPolicySpec) GetType() VcenterVmStoragePolicyDiskPolicySpecPolicyType {
	if o == nil {
		var ret VcenterVmStoragePolicyDiskPolicySpecPolicyType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *VcenterVmStoragePolicyDiskPolicySpec) GetTypeOk() (*VcenterVmStoragePolicyDiskPolicySpecPolicyType, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *VcenterVmStoragePolicyDiskPolicySpec) SetType(v VcenterVmStoragePolicyDiskPolicySpecPolicyType) {
	o.Type = v
}

// GetPolicy returns the Policy field value if set, zero value otherwise.
func (o *VcenterVmStoragePolicyDiskPolicySpec) GetPolicy() string {
	if o == nil || o.Policy == nil {
		var ret string
		return ret
	}
	return *o.Policy
}

// GetPolicyOk returns a tuple with the Policy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmStoragePolicyDiskPolicySpec) GetPolicyOk() (*string, bool) {
	if o == nil || o.Policy == nil {
		return nil, false
	}
	return o.Policy, true
}

// HasPolicy returns a boolean if a field has been set.
func (o *VcenterVmStoragePolicyDiskPolicySpec) HasPolicy() bool {
	if o != nil && o.Policy != nil {
		return true
	}

	return false
}

// SetPolicy gets a reference to the given string and assigns it to the Policy field.
func (o *VcenterVmStoragePolicyDiskPolicySpec) SetPolicy(v string) {
	o.Policy = &v
}

func (o VcenterVmStoragePolicyDiskPolicySpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if o.Policy != nil {
		toSerialize["policy"] = o.Policy
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterVmStoragePolicyDiskPolicySpec struct {
	value *VcenterVmStoragePolicyDiskPolicySpec
	isSet bool
}

func (v NullableVcenterVmStoragePolicyDiskPolicySpec) Get() *VcenterVmStoragePolicyDiskPolicySpec {
	return v.value
}

func (v *NullableVcenterVmStoragePolicyDiskPolicySpec) Set(val *VcenterVmStoragePolicyDiskPolicySpec) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterVmStoragePolicyDiskPolicySpec) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterVmStoragePolicyDiskPolicySpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterVmStoragePolicyDiskPolicySpec(val *VcenterVmStoragePolicyDiskPolicySpec) *NullableVcenterVmStoragePolicyDiskPolicySpec {
	return &NullableVcenterVmStoragePolicyDiskPolicySpec{value: val, isSet: true}
}

func (v NullableVcenterVmStoragePolicyDiskPolicySpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterVmStoragePolicyDiskPolicySpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


