/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterVmTemplateLibraryItemsGuestCustomizationSpec struct for VcenterVmTemplateLibraryItemsGuestCustomizationSpec
type VcenterVmTemplateLibraryItemsGuestCustomizationSpec struct {
	// Name of the customization specification.
	Name *string `json:"name,omitempty"`
}

// NewVcenterVmTemplateLibraryItemsGuestCustomizationSpec instantiates a new VcenterVmTemplateLibraryItemsGuestCustomizationSpec object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterVmTemplateLibraryItemsGuestCustomizationSpec() *VcenterVmTemplateLibraryItemsGuestCustomizationSpec {
	this := VcenterVmTemplateLibraryItemsGuestCustomizationSpec{}
	return &this
}

// NewVcenterVmTemplateLibraryItemsGuestCustomizationSpecWithDefaults instantiates a new VcenterVmTemplateLibraryItemsGuestCustomizationSpec object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterVmTemplateLibraryItemsGuestCustomizationSpecWithDefaults() *VcenterVmTemplateLibraryItemsGuestCustomizationSpec {
	this := VcenterVmTemplateLibraryItemsGuestCustomizationSpec{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) SetName(v string) {
	o.Name = &v
}

func (o VcenterVmTemplateLibraryItemsGuestCustomizationSpec) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec struct {
	value *VcenterVmTemplateLibraryItemsGuestCustomizationSpec
	isSet bool
}

func (v NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) Get() *VcenterVmTemplateLibraryItemsGuestCustomizationSpec {
	return v.value
}

func (v *NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) Set(val *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec(val *VcenterVmTemplateLibraryItemsGuestCustomizationSpec) *NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec {
	return &NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec{value: val, isSet: true}
}

func (v NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterVmTemplateLibraryItemsGuestCustomizationSpec) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


