/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// VcenterVmGuestFilesystemFilesFileAttributesInfo struct for VcenterVmGuestFilesystemFilesFileAttributesInfo
type VcenterVmGuestFilesystemFilesFileAttributesInfo struct {
	// The date and time the file was last modified.
	LastModified time.Time `json:"last_modified"`
	// The date and time the file was last accessed.
	LastAccessed time.Time `json:"last_accessed"`
	// The target for the file if it's a symbolic link. This is currently only set for Posix guest operating systems, but may be supported in the future on Windows guest operating systems that support symbolic links. Set if the file is a symbolic link.
	SymlinkTarget *string `json:"symlink_target,omitempty"`
	FilesystemFamily VcenterVmGuestFilesystemFilesFilesystemFamily `json:"filesystem_family"`
	WinAttributes *VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo `json:"win_attributes,omitempty"`
	PosixAttributes *VcenterVmGuestFilesystemFilesPosixFileAttributesInfo `json:"posix_attributes,omitempty"`
}

// NewVcenterVmGuestFilesystemFilesFileAttributesInfo instantiates a new VcenterVmGuestFilesystemFilesFileAttributesInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterVmGuestFilesystemFilesFileAttributesInfo(lastModified time.Time, lastAccessed time.Time, filesystemFamily VcenterVmGuestFilesystemFilesFilesystemFamily) *VcenterVmGuestFilesystemFilesFileAttributesInfo {
	this := VcenterVmGuestFilesystemFilesFileAttributesInfo{}
	this.LastModified = lastModified
	this.LastAccessed = lastAccessed
	this.FilesystemFamily = filesystemFamily
	return &this
}

// NewVcenterVmGuestFilesystemFilesFileAttributesInfoWithDefaults instantiates a new VcenterVmGuestFilesystemFilesFileAttributesInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterVmGuestFilesystemFilesFileAttributesInfoWithDefaults() *VcenterVmGuestFilesystemFilesFileAttributesInfo {
	this := VcenterVmGuestFilesystemFilesFileAttributesInfo{}
	return &this
}

// GetLastModified returns the LastModified field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetLastModified() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetLastModifiedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastModified, true
}

// SetLastModified sets field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetLastModified(v time.Time) {
	o.LastModified = v
}

// GetLastAccessed returns the LastAccessed field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetLastAccessed() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.LastAccessed
}

// GetLastAccessedOk returns a tuple with the LastAccessed field value
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetLastAccessedOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.LastAccessed, true
}

// SetLastAccessed sets field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetLastAccessed(v time.Time) {
	o.LastAccessed = v
}

// GetSymlinkTarget returns the SymlinkTarget field value if set, zero value otherwise.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetSymlinkTarget() string {
	if o == nil || o.SymlinkTarget == nil {
		var ret string
		return ret
	}
	return *o.SymlinkTarget
}

// GetSymlinkTargetOk returns a tuple with the SymlinkTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetSymlinkTargetOk() (*string, bool) {
	if o == nil || o.SymlinkTarget == nil {
		return nil, false
	}
	return o.SymlinkTarget, true
}

// HasSymlinkTarget returns a boolean if a field has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) HasSymlinkTarget() bool {
	if o != nil && o.SymlinkTarget != nil {
		return true
	}

	return false
}

// SetSymlinkTarget gets a reference to the given string and assigns it to the SymlinkTarget field.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetSymlinkTarget(v string) {
	o.SymlinkTarget = &v
}

// GetFilesystemFamily returns the FilesystemFamily field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetFilesystemFamily() VcenterVmGuestFilesystemFilesFilesystemFamily {
	if o == nil {
		var ret VcenterVmGuestFilesystemFilesFilesystemFamily
		return ret
	}

	return o.FilesystemFamily
}

// GetFilesystemFamilyOk returns a tuple with the FilesystemFamily field value
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetFilesystemFamilyOk() (*VcenterVmGuestFilesystemFilesFilesystemFamily, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FilesystemFamily, true
}

// SetFilesystemFamily sets field value
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetFilesystemFamily(v VcenterVmGuestFilesystemFilesFilesystemFamily) {
	o.FilesystemFamily = v
}

// GetWinAttributes returns the WinAttributes field value if set, zero value otherwise.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetWinAttributes() VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo {
	if o == nil || o.WinAttributes == nil {
		var ret VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo
		return ret
	}
	return *o.WinAttributes
}

// GetWinAttributesOk returns a tuple with the WinAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetWinAttributesOk() (*VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo, bool) {
	if o == nil || o.WinAttributes == nil {
		return nil, false
	}
	return o.WinAttributes, true
}

// HasWinAttributes returns a boolean if a field has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) HasWinAttributes() bool {
	if o != nil && o.WinAttributes != nil {
		return true
	}

	return false
}

// SetWinAttributes gets a reference to the given VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo and assigns it to the WinAttributes field.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetWinAttributes(v VcenterVmGuestFilesystemFilesWindowsFileAttributesInfo) {
	o.WinAttributes = &v
}

// GetPosixAttributes returns the PosixAttributes field value if set, zero value otherwise.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetPosixAttributes() VcenterVmGuestFilesystemFilesPosixFileAttributesInfo {
	if o == nil || o.PosixAttributes == nil {
		var ret VcenterVmGuestFilesystemFilesPosixFileAttributesInfo
		return ret
	}
	return *o.PosixAttributes
}

// GetPosixAttributesOk returns a tuple with the PosixAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) GetPosixAttributesOk() (*VcenterVmGuestFilesystemFilesPosixFileAttributesInfo, bool) {
	if o == nil || o.PosixAttributes == nil {
		return nil, false
	}
	return o.PosixAttributes, true
}

// HasPosixAttributes returns a boolean if a field has been set.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) HasPosixAttributes() bool {
	if o != nil && o.PosixAttributes != nil {
		return true
	}

	return false
}

// SetPosixAttributes gets a reference to the given VcenterVmGuestFilesystemFilesPosixFileAttributesInfo and assigns it to the PosixAttributes field.
func (o *VcenterVmGuestFilesystemFilesFileAttributesInfo) SetPosixAttributes(v VcenterVmGuestFilesystemFilesPosixFileAttributesInfo) {
	o.PosixAttributes = &v
}

func (o VcenterVmGuestFilesystemFilesFileAttributesInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["last_modified"] = o.LastModified
	}
	if true {
		toSerialize["last_accessed"] = o.LastAccessed
	}
	if o.SymlinkTarget != nil {
		toSerialize["symlink_target"] = o.SymlinkTarget
	}
	if true {
		toSerialize["filesystem_family"] = o.FilesystemFamily
	}
	if o.WinAttributes != nil {
		toSerialize["win_attributes"] = o.WinAttributes
	}
	if o.PosixAttributes != nil {
		toSerialize["posix_attributes"] = o.PosixAttributes
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterVmGuestFilesystemFilesFileAttributesInfo struct {
	value *VcenterVmGuestFilesystemFilesFileAttributesInfo
	isSet bool
}

func (v NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) Get() *VcenterVmGuestFilesystemFilesFileAttributesInfo {
	return v.value
}

func (v *NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) Set(val *VcenterVmGuestFilesystemFilesFileAttributesInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterVmGuestFilesystemFilesFileAttributesInfo(val *VcenterVmGuestFilesystemFilesFileAttributesInfo) *NullableVcenterVmGuestFilesystemFilesFileAttributesInfo {
	return &NullableVcenterVmGuestFilesystemFilesFileAttributesInfo{value: val, isSet: true}
}

func (v NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterVmGuestFilesystemFilesFileAttributesInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


