/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp struct for VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp
type VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp struct {
	Value VcenterHvcLinksSyncProvidersInfo `json:"value"`
}

// NewVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp instantiates a new VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp(value VcenterHvcLinksSyncProvidersInfo) *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp {
	this := VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp{}
	this.Value = value
	return &this
}

// NewVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersRespWithDefaults instantiates a new VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersRespWithDefaults() *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp {
	this := VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp{}
	return &this
}

// GetValue returns the Value field value
func (o *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) GetValue() VcenterHvcLinksSyncProvidersInfo {
	if o == nil {
		var ret VcenterHvcLinksSyncProvidersInfo
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) GetValueOk() (*VcenterHvcLinksSyncProvidersInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) SetValue(v VcenterHvcLinksSyncProvidersInfo) {
	o.Value = v
}

func (o VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp struct {
	value *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp
	isSet bool
}

func (v NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) Get() *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp {
	return v.value
}

func (v *NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) Set(val *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp(val *VcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) *NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp {
	return &NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp{value: val, isSet: true}
}

func (v NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterHvcLinksSyncProvidersGetHvcLinksSyncProvidersResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


