/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr struct for VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr
type VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr struct {
	Spec *VcenterCertificateManagementVcenterTlsCsrSpec `json:"spec,omitempty"`
}

// NewVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr instantiates a new VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr() *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr {
	this := VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr{}
	return &this
}

// NewVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsrWithDefaults instantiates a new VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsrWithDefaults() *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr {
	this := VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) GetSpec() VcenterCertificateManagementVcenterTlsCsrSpec {
	if o == nil || o.Spec == nil {
		var ret VcenterCertificateManagementVcenterTlsCsrSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) GetSpecOk() (*VcenterCertificateManagementVcenterTlsCsrSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given VcenterCertificateManagementVcenterTlsCsrSpec and assigns it to the Spec field.
func (o *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) SetSpec(v VcenterCertificateManagementVcenterTlsCsrSpec) {
	o.Spec = &v
}

func (o VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr struct {
	value *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr
	isSet bool
}

func (v NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) Get() *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr {
	return v.value
}

func (v *NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) Set(val *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr(val *VcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) *NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr {
	return &NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr{value: val, isSet: true}
}

func (v NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterCertificateManagementVcenterTlsCsrCreateCertificateManagementVcenterTlsCsr) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


