/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentMigrateCheckDeploymentMigrateResp struct for VcenterDeploymentMigrateCheckDeploymentMigrateResp
type VcenterDeploymentMigrateCheckDeploymentMigrateResp struct {
	Value VcenterDeploymentCheckInfo `json:"value"`
}

// NewVcenterDeploymentMigrateCheckDeploymentMigrateResp instantiates a new VcenterDeploymentMigrateCheckDeploymentMigrateResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentMigrateCheckDeploymentMigrateResp(value VcenterDeploymentCheckInfo) *VcenterDeploymentMigrateCheckDeploymentMigrateResp {
	this := VcenterDeploymentMigrateCheckDeploymentMigrateResp{}
	this.Value = value
	return &this
}

// NewVcenterDeploymentMigrateCheckDeploymentMigrateRespWithDefaults instantiates a new VcenterDeploymentMigrateCheckDeploymentMigrateResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentMigrateCheckDeploymentMigrateRespWithDefaults() *VcenterDeploymentMigrateCheckDeploymentMigrateResp {
	this := VcenterDeploymentMigrateCheckDeploymentMigrateResp{}
	return &this
}

// GetValue returns the Value field value
func (o *VcenterDeploymentMigrateCheckDeploymentMigrateResp) GetValue() VcenterDeploymentCheckInfo {
	if o == nil {
		var ret VcenterDeploymentCheckInfo
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentMigrateCheckDeploymentMigrateResp) GetValueOk() (*VcenterDeploymentCheckInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VcenterDeploymentMigrateCheckDeploymentMigrateResp) SetValue(v VcenterDeploymentCheckInfo) {
	o.Value = v
}

func (o VcenterDeploymentMigrateCheckDeploymentMigrateResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp struct {
	value *VcenterDeploymentMigrateCheckDeploymentMigrateResp
	isSet bool
}

func (v NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) Get() *VcenterDeploymentMigrateCheckDeploymentMigrateResp {
	return v.value
}

func (v *NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) Set(val *VcenterDeploymentMigrateCheckDeploymentMigrateResp) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentMigrateCheckDeploymentMigrateResp(val *VcenterDeploymentMigrateCheckDeploymentMigrateResp) *NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp {
	return &NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp{value: val, isSet: true}
}

func (v NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentMigrateCheckDeploymentMigrateResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


