/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc struct for VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc
type VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc struct {
	Spec *VcenterDeploymentRemotePscSpec `json:"spec,omitempty"`
}

// NewVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc instantiates a new VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc() *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc {
	this := VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc{}
	return &this
}

// NewVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePscWithDefaults instantiates a new VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePscWithDefaults() *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc {
	this := VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc{}
	return &this
}

// GetSpec returns the Spec field value if set, zero value otherwise.
func (o *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) GetSpec() VcenterDeploymentRemotePscSpec {
	if o == nil || o.Spec == nil {
		var ret VcenterDeploymentRemotePscSpec
		return ret
	}
	return *o.Spec
}

// GetSpecOk returns a tuple with the Spec field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) GetSpecOk() (*VcenterDeploymentRemotePscSpec, bool) {
	if o == nil || o.Spec == nil {
		return nil, false
	}
	return o.Spec, true
}

// HasSpec returns a boolean if a field has been set.
func (o *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) HasSpec() bool {
	if o != nil && o.Spec != nil {
		return true
	}

	return false
}

// SetSpec gets a reference to the given VcenterDeploymentRemotePscSpec and assigns it to the Spec field.
func (o *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) SetSpec(v VcenterDeploymentRemotePscSpec) {
	o.Spec = &v
}

func (o VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Spec != nil {
		toSerialize["spec"] = o.Spec
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc struct {
	value *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc
	isSet bool
}

func (v NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) Get() *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc {
	return v.value
}

func (v *NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) Set(val *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc(val *VcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) *NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc {
	return &NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc{value: val, isSet: true}
}

func (v NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterDeploymentInstallRemotePscCheckDeploymentInstallRemotePsc) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


