/*
vcenter

VMware vCenter Server provides a centralized platform for managing your VMware vSphere environments

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// VcenterContentRegistriesHarborGetContentRegistriesHarborResp struct for VcenterContentRegistriesHarborGetContentRegistriesHarborResp
type VcenterContentRegistriesHarborGetContentRegistriesHarborResp struct {
	Value VcenterContentRegistriesHarborInfo `json:"value"`
}

// NewVcenterContentRegistriesHarborGetContentRegistriesHarborResp instantiates a new VcenterContentRegistriesHarborGetContentRegistriesHarborResp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVcenterContentRegistriesHarborGetContentRegistriesHarborResp(value VcenterContentRegistriesHarborInfo) *VcenterContentRegistriesHarborGetContentRegistriesHarborResp {
	this := VcenterContentRegistriesHarborGetContentRegistriesHarborResp{}
	this.Value = value
	return &this
}

// NewVcenterContentRegistriesHarborGetContentRegistriesHarborRespWithDefaults instantiates a new VcenterContentRegistriesHarborGetContentRegistriesHarborResp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVcenterContentRegistriesHarborGetContentRegistriesHarborRespWithDefaults() *VcenterContentRegistriesHarborGetContentRegistriesHarborResp {
	this := VcenterContentRegistriesHarborGetContentRegistriesHarborResp{}
	return &this
}

// GetValue returns the Value field value
func (o *VcenterContentRegistriesHarborGetContentRegistriesHarborResp) GetValue() VcenterContentRegistriesHarborInfo {
	if o == nil {
		var ret VcenterContentRegistriesHarborInfo
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *VcenterContentRegistriesHarborGetContentRegistriesHarborResp) GetValueOk() (*VcenterContentRegistriesHarborInfo, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *VcenterContentRegistriesHarborGetContentRegistriesHarborResp) SetValue(v VcenterContentRegistriesHarborInfo) {
	o.Value = v
}

func (o VcenterContentRegistriesHarborGetContentRegistriesHarborResp) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp struct {
	value *VcenterContentRegistriesHarborGetContentRegistriesHarborResp
	isSet bool
}

func (v NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) Get() *VcenterContentRegistriesHarborGetContentRegistriesHarborResp {
	return v.value
}

func (v *NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) Set(val *VcenterContentRegistriesHarborGetContentRegistriesHarborResp) {
	v.value = val
	v.isSet = true
}

func (v NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) IsSet() bool {
	return v.isSet
}

func (v *NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp(val *VcenterContentRegistriesHarborGetContentRegistriesHarborResp) *NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp {
	return &NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp{value: val, isSet: true}
}

func (v NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVcenterContentRegistriesHarborGetContentRegistriesHarborResp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


